<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <Authors>Andrea Luciano Damico</Authors>
        <Description>Provides an Avalonia value converter that converts an ISO 3166-1 alpha-2 country code into an Avalonia Svg of that country's flag.</Description>
        <PackageIcon>globe.png</PackageIcon>
        <Version>11.3.2</Version>
        <Title>Avalonia.Lipis.Flags</Title>
        <PackageProjectUrl>https://github.com/ALDamico/Avalonia.Lipis.Flags</PackageProjectUrl>
        <PackageLicenseUrl>https://github.com/ALDamico/Avalonia.Lipis.Flags/blob/master/LICENSE</PackageLicenseUrl>
        <RepositoryUrl>https://github.com/ALDamico/Avalonia.Lipis.Flags</RepositoryUrl>
        <RepositoryType>github</RepositoryType>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.3.2"/>
        <PackageReference Include="Enums.NET" Version="5.0.0"/>
    </ItemGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\1x1\ad.svg"/>
        <AvaloniaResource Include="Assets\1x1\ae.svg"/>
        <AvaloniaResource Include="Assets\1x1\af.svg"/>
        <AvaloniaResource Include="Assets\1x1\ag.svg"/>
        <AvaloniaResource Include="Assets\1x1\ai.svg"/>
        <AvaloniaResource Include="Assets\1x1\al.svg"/>
        <AvaloniaResource Include="Assets\1x1\am.svg"/>
        <AvaloniaResource Include="Assets\1x1\ao.svg"/>
        <AvaloniaResource Include="Assets\1x1\aq.svg"/>
        <AvaloniaResource Include="Assets\1x1\ar.svg"/>
        <AvaloniaResource Include="Assets\1x1\arab.svg"/>
        <AvaloniaResource Include="Assets\1x1\as.svg"/>
        <AvaloniaResource Include="Assets\1x1\asean.svg"/>
        <AvaloniaResource Include="Assets\1x1\at.svg"/>
        <AvaloniaResource Include="Assets\1x1\au.svg"/>
        <AvaloniaResource Include="Assets\1x1\aw.svg"/>
        <AvaloniaResource Include="Assets\1x1\ax.svg"/>
        <AvaloniaResource Include="Assets\1x1\az.svg"/>
        <AvaloniaResource Include="Assets\1x1\ba.svg"/>
        <AvaloniaResource Include="Assets\1x1\bb.svg"/>
        <AvaloniaResource Include="Assets\1x1\bd.svg"/>
        <AvaloniaResource Include="Assets\1x1\be.svg"/>
        <AvaloniaResource Include="Assets\1x1\bf.svg"/>
        <AvaloniaResource Include="Assets\1x1\bg.svg"/>
        <AvaloniaResource Include="Assets\1x1\bh.svg"/>
        <AvaloniaResource Include="Assets\1x1\bi.svg"/>
        <AvaloniaResource Include="Assets\1x1\bj.svg"/>
        <AvaloniaResource Include="Assets\1x1\bl.svg"/>
        <AvaloniaResource Include="Assets\1x1\bm.svg"/>
        <AvaloniaResource Include="Assets\1x1\bn.svg"/>
        <AvaloniaResource Include="Assets\1x1\bo.svg"/>
        <AvaloniaResource Include="Assets\1x1\bq.svg"/>
        <AvaloniaResource Include="Assets\1x1\br.svg"/>
        <AvaloniaResource Include="Assets\1x1\bs.svg"/>
        <AvaloniaResource Include="Assets\1x1\bt.svg"/>
        <AvaloniaResource Include="Assets\1x1\bv.svg"/>
        <AvaloniaResource Include="Assets\1x1\bw.svg"/>
        <AvaloniaResource Include="Assets\1x1\by.svg"/>
        <AvaloniaResource Include="Assets\1x1\bz.svg"/>
        <AvaloniaResource Include="Assets\1x1\ca.svg"/>
        <AvaloniaResource Include="Assets\1x1\cc.svg"/>
        <AvaloniaResource Include="Assets\1x1\cd.svg"/>
        <AvaloniaResource Include="Assets\1x1\cefta.svg"/>
        <AvaloniaResource Include="Assets\1x1\cf.svg"/>
        <AvaloniaResource Include="Assets\1x1\cg.svg"/>
        <AvaloniaResource Include="Assets\1x1\ch.svg"/>
        <AvaloniaResource Include="Assets\1x1\ci.svg"/>
        <AvaloniaResource Include="Assets\1x1\ck.svg"/>
        <AvaloniaResource Include="Assets\1x1\cl.svg"/>
        <AvaloniaResource Include="Assets\1x1\cm.svg"/>
        <AvaloniaResource Include="Assets\1x1\cn.svg"/>
        <AvaloniaResource Include="Assets\1x1\co.svg"/>
        <AvaloniaResource Include="Assets\1x1\cp.svg"/>
        <AvaloniaResource Include="Assets\1x1\cr.svg"/>
        <AvaloniaResource Include="Assets\1x1\cu.svg"/>
        <AvaloniaResource Include="Assets\1x1\cv.svg"/>
        <AvaloniaResource Include="Assets\1x1\cw.svg"/>
        <AvaloniaResource Include="Assets\1x1\cx.svg"/>
        <AvaloniaResource Include="Assets\1x1\cy.svg"/>
        <AvaloniaResource Include="Assets\1x1\cz.svg"/>
        <AvaloniaResource Include="Assets\1x1\de.svg"/>
        <AvaloniaResource Include="Assets\1x1\dg.svg"/>
        <AvaloniaResource Include="Assets\1x1\dj.svg"/>
        <AvaloniaResource Include="Assets\1x1\dk.svg"/>
        <AvaloniaResource Include="Assets\1x1\dm.svg"/>
        <AvaloniaResource Include="Assets\1x1\do.svg"/>
        <AvaloniaResource Include="Assets\1x1\dz.svg"/>
        <AvaloniaResource Include="Assets\1x1\eac.svg"/>
        <AvaloniaResource Include="Assets\1x1\ec.svg"/>
        <AvaloniaResource Include="Assets\1x1\ee.svg"/>
        <AvaloniaResource Include="Assets\1x1\eg.svg"/>
        <AvaloniaResource Include="Assets\1x1\eh.svg"/>
        <AvaloniaResource Include="Assets\1x1\er.svg"/>
        <AvaloniaResource Include="Assets\1x1\es.svg"/>
        <AvaloniaResource Include="Assets\1x1\es-ct.svg"/>
        <AvaloniaResource Include="Assets\1x1\es-ga.svg"/>
        <AvaloniaResource Include="Assets\1x1\es-pv.svg"/>
        <AvaloniaResource Include="Assets\1x1\et.svg"/>
        <AvaloniaResource Include="Assets\1x1\eu.svg"/>
        <AvaloniaResource Include="Assets\1x1\fi.svg"/>
        <AvaloniaResource Include="Assets\1x1\fj.svg"/>
        <AvaloniaResource Include="Assets\1x1\fk.svg"/>
        <AvaloniaResource Include="Assets\1x1\fm.svg"/>
        <AvaloniaResource Include="Assets\1x1\fo.svg"/>
        <AvaloniaResource Include="Assets\1x1\fr.svg"/>
        <AvaloniaResource Include="Assets\1x1\ga.svg"/>
        <AvaloniaResource Include="Assets\1x1\gb.svg"/>
        <AvaloniaResource Include="Assets\1x1\gb-eng.svg"/>
        <AvaloniaResource Include="Assets\1x1\gb-nir.svg"/>
        <AvaloniaResource Include="Assets\1x1\gb-sct.svg"/>
        <AvaloniaResource Include="Assets\1x1\gb-wls.svg"/>
        <AvaloniaResource Include="Assets\1x1\gd.svg"/>
        <AvaloniaResource Include="Assets\1x1\ge.svg"/>
        <AvaloniaResource Include="Assets\1x1\gf.svg"/>
        <AvaloniaResource Include="Assets\1x1\gg.svg"/>
        <AvaloniaResource Include="Assets\1x1\gh.svg"/>
        <AvaloniaResource Include="Assets\1x1\gi.svg"/>
        <AvaloniaResource Include="Assets\1x1\gl.svg"/>
        <AvaloniaResource Include="Assets\1x1\gm.svg"/>
        <AvaloniaResource Include="Assets\1x1\gn.svg"/>
        <AvaloniaResource Include="Assets\1x1\gp.svg"/>
        <AvaloniaResource Include="Assets\1x1\gq.svg"/>
        <AvaloniaResource Include="Assets\1x1\gr.svg"/>
        <AvaloniaResource Include="Assets\1x1\gs.svg"/>
        <AvaloniaResource Include="Assets\1x1\gt.svg"/>
        <AvaloniaResource Include="Assets\1x1\gu.svg"/>
        <AvaloniaResource Include="Assets\1x1\gw.svg"/>
        <AvaloniaResource Include="Assets\1x1\gy.svg"/>
        <AvaloniaResource Include="Assets\1x1\hk.svg"/>
        <AvaloniaResource Include="Assets\1x1\hm.svg"/>
        <AvaloniaResource Include="Assets\1x1\hn.svg"/>
        <AvaloniaResource Include="Assets\1x1\hr.svg"/>
        <AvaloniaResource Include="Assets\1x1\ht.svg"/>
        <AvaloniaResource Include="Assets\1x1\hu.svg"/>
        <AvaloniaResource Include="Assets\1x1\ic.svg"/>
        <AvaloniaResource Include="Assets\1x1\id.svg"/>
        <AvaloniaResource Include="Assets\1x1\ie.svg"/>
        <AvaloniaResource Include="Assets\1x1\il.svg"/>
        <AvaloniaResource Include="Assets\1x1\im.svg"/>
        <AvaloniaResource Include="Assets\1x1\in.svg"/>
        <AvaloniaResource Include="Assets\1x1\io.svg"/>
        <AvaloniaResource Include="Assets\1x1\iq.svg"/>
        <AvaloniaResource Include="Assets\1x1\ir.svg"/>
        <AvaloniaResource Include="Assets\1x1\is.svg"/>
        <AvaloniaResource Include="Assets\1x1\it.svg"/>
        <AvaloniaResource Include="Assets\1x1\je.svg"/>
        <AvaloniaResource Include="Assets\1x1\jm.svg"/>
        <AvaloniaResource Include="Assets\1x1\jo.svg"/>
        <AvaloniaResource Include="Assets\1x1\jp.svg"/>
        <AvaloniaResource Include="Assets\1x1\ke.svg"/>
        <AvaloniaResource Include="Assets\1x1\kg.svg"/>
        <AvaloniaResource Include="Assets\1x1\kh.svg"/>
        <AvaloniaResource Include="Assets\1x1\ki.svg"/>
        <AvaloniaResource Include="Assets\1x1\km.svg"/>
        <AvaloniaResource Include="Assets\1x1\kn.svg"/>
        <AvaloniaResource Include="Assets\1x1\kp.svg"/>
        <AvaloniaResource Include="Assets\1x1\kr.svg"/>
        <AvaloniaResource Include="Assets\1x1\kw.svg"/>
        <AvaloniaResource Include="Assets\1x1\ky.svg"/>
        <AvaloniaResource Include="Assets\1x1\kz.svg"/>
        <AvaloniaResource Include="Assets\1x1\la.svg"/>
        <AvaloniaResource Include="Assets\1x1\lb.svg"/>
        <AvaloniaResource Include="Assets\1x1\lc.svg"/>
        <AvaloniaResource Include="Assets\1x1\li.svg"/>
        <AvaloniaResource Include="Assets\1x1\lk.svg"/>
        <AvaloniaResource Include="Assets\1x1\lr.svg"/>
        <AvaloniaResource Include="Assets\1x1\ls.svg"/>
        <AvaloniaResource Include="Assets\1x1\lt.svg"/>
        <AvaloniaResource Include="Assets\1x1\lu.svg"/>
        <AvaloniaResource Include="Assets\1x1\lv.svg"/>
        <AvaloniaResource Include="Assets\1x1\ly.svg"/>
        <AvaloniaResource Include="Assets\1x1\ma.svg"/>
        <AvaloniaResource Include="Assets\1x1\mc.svg"/>
        <AvaloniaResource Include="Assets\1x1\md.svg"/>
        <AvaloniaResource Include="Assets\1x1\me.svg"/>
        <AvaloniaResource Include="Assets\1x1\mf.svg"/>
        <AvaloniaResource Include="Assets\1x1\mg.svg"/>
        <AvaloniaResource Include="Assets\1x1\mh.svg"/>
        <AvaloniaResource Include="Assets\1x1\mk.svg"/>
        <AvaloniaResource Include="Assets\1x1\ml.svg"/>
        <AvaloniaResource Include="Assets\1x1\mm.svg"/>
        <AvaloniaResource Include="Assets\1x1\mn.svg"/>
        <AvaloniaResource Include="Assets\1x1\mo.svg"/>
        <AvaloniaResource Include="Assets\1x1\mp.svg"/>
        <AvaloniaResource Include="Assets\1x1\mq.svg"/>
        <AvaloniaResource Include="Assets\1x1\mr.svg"/>
        <AvaloniaResource Include="Assets\1x1\ms.svg"/>
        <AvaloniaResource Include="Assets\1x1\mt.svg"/>
        <AvaloniaResource Include="Assets\1x1\mu.svg"/>
        <AvaloniaResource Include="Assets\1x1\mv.svg"/>
        <AvaloniaResource Include="Assets\1x1\mw.svg"/>
        <AvaloniaResource Include="Assets\1x1\mx.svg"/>
        <AvaloniaResource Include="Assets\1x1\my.svg"/>
        <AvaloniaResource Include="Assets\1x1\mz.svg"/>
        <AvaloniaResource Include="Assets\1x1\na.svg"/>
        <AvaloniaResource Include="Assets\1x1\nc.svg"/>
        <AvaloniaResource Include="Assets\1x1\ne.svg"/>
        <AvaloniaResource Include="Assets\1x1\nf.svg"/>
        <AvaloniaResource Include="Assets\1x1\ng.svg"/>
        <AvaloniaResource Include="Assets\1x1\ni.svg"/>
        <AvaloniaResource Include="Assets\1x1\nl.svg"/>
        <AvaloniaResource Include="Assets\1x1\no.svg"/>
        <AvaloniaResource Include="Assets\1x1\np.svg"/>
        <AvaloniaResource Include="Assets\1x1\nr.svg"/>
        <AvaloniaResource Include="Assets\1x1\nu.svg"/>
        <AvaloniaResource Include="Assets\1x1\nz.svg"/>
        <AvaloniaResource Include="Assets\1x1\om.svg"/>
        <AvaloniaResource Include="Assets\1x1\pa.svg"/>
        <AvaloniaResource Include="Assets\1x1\pc.svg"/>
        <AvaloniaResource Include="Assets\1x1\pe.svg"/>
        <AvaloniaResource Include="Assets\1x1\pf.svg"/>
        <AvaloniaResource Include="Assets\1x1\pg.svg"/>
        <AvaloniaResource Include="Assets\1x1\ph.svg"/>
        <AvaloniaResource Include="Assets\1x1\pk.svg"/>
        <AvaloniaResource Include="Assets\1x1\pl.svg"/>
        <AvaloniaResource Include="Assets\1x1\pm.svg"/>
        <AvaloniaResource Include="Assets\1x1\pn.svg"/>
        <AvaloniaResource Include="Assets\1x1\pr.svg"/>
        <AvaloniaResource Include="Assets\1x1\ps.svg"/>
        <AvaloniaResource Include="Assets\1x1\pt.svg"/>
        <AvaloniaResource Include="Assets\1x1\pw.svg"/>
        <AvaloniaResource Include="Assets\1x1\py.svg"/>
        <AvaloniaResource Include="Assets\1x1\qa.svg"/>
        <AvaloniaResource Include="Assets\1x1\re.svg"/>
        <AvaloniaResource Include="Assets\1x1\ro.svg"/>
        <AvaloniaResource Include="Assets\1x1\rs.svg"/>
        <AvaloniaResource Include="Assets\1x1\ru.svg"/>
        <AvaloniaResource Include="Assets\1x1\rw.svg"/>
        <AvaloniaResource Include="Assets\1x1\sa.svg"/>
        <AvaloniaResource Include="Assets\1x1\sb.svg"/>
        <AvaloniaResource Include="Assets\1x1\sc.svg"/>
        <AvaloniaResource Include="Assets\1x1\sd.svg"/>
        <AvaloniaResource Include="Assets\1x1\se.svg"/>
        <AvaloniaResource Include="Assets\1x1\sg.svg"/>
        <AvaloniaResource Include="Assets\1x1\sh.svg"/>
        <AvaloniaResource Include="Assets\1x1\sh-ac.svg"/>
        <AvaloniaResource Include="Assets\1x1\sh-hl.svg"/>
        <AvaloniaResource Include="Assets\1x1\sh-ta.svg"/>
        <AvaloniaResource Include="Assets\1x1\si.svg"/>
        <AvaloniaResource Include="Assets\1x1\sj.svg"/>
        <AvaloniaResource Include="Assets\1x1\sk.svg"/>
        <AvaloniaResource Include="Assets\1x1\sl.svg"/>
        <AvaloniaResource Include="Assets\1x1\sm.svg"/>
        <AvaloniaResource Include="Assets\1x1\sn.svg"/>
        <AvaloniaResource Include="Assets\1x1\so.svg"/>
        <AvaloniaResource Include="Assets\1x1\sr.svg"/>
        <AvaloniaResource Include="Assets\1x1\ss.svg"/>
        <AvaloniaResource Include="Assets\1x1\st.svg"/>
        <AvaloniaResource Include="Assets\1x1\sv.svg"/>
        <AvaloniaResource Include="Assets\1x1\sx.svg"/>
        <AvaloniaResource Include="Assets\1x1\sy.svg"/>
        <AvaloniaResource Include="Assets\1x1\sz.svg"/>
        <AvaloniaResource Include="Assets\1x1\tc.svg"/>
        <AvaloniaResource Include="Assets\1x1\td.svg"/>
        <AvaloniaResource Include="Assets\1x1\tf.svg"/>
        <AvaloniaResource Include="Assets\1x1\tg.svg"/>
        <AvaloniaResource Include="Assets\1x1\th.svg"/>
        <AvaloniaResource Include="Assets\1x1\tj.svg"/>
        <AvaloniaResource Include="Assets\1x1\tk.svg"/>
        <AvaloniaResource Include="Assets\1x1\tl.svg"/>
        <AvaloniaResource Include="Assets\1x1\tm.svg"/>
        <AvaloniaResource Include="Assets\1x1\tn.svg"/>
        <AvaloniaResource Include="Assets\1x1\to.svg"/>
        <AvaloniaResource Include="Assets\1x1\tr.svg"/>
        <AvaloniaResource Include="Assets\1x1\tt.svg"/>
        <AvaloniaResource Include="Assets\1x1\tv.svg"/>
        <AvaloniaResource Include="Assets\1x1\tw.svg"/>
        <AvaloniaResource Include="Assets\1x1\tz.svg"/>
        <AvaloniaResource Include="Assets\1x1\ua.svg"/>
        <AvaloniaResource Include="Assets\1x1\ug.svg"/>
        <AvaloniaResource Include="Assets\1x1\um.svg"/>
        <AvaloniaResource Include="Assets\1x1\un.svg"/>
        <AvaloniaResource Include="Assets\1x1\us.svg"/>
        <AvaloniaResource Include="Assets\1x1\uy.svg"/>
        <AvaloniaResource Include="Assets\1x1\uz.svg"/>
        <AvaloniaResource Include="Assets\1x1\va.svg"/>
        <AvaloniaResource Include="Assets\1x1\vc.svg"/>
        <AvaloniaResource Include="Assets\1x1\ve.svg"/>
        <AvaloniaResource Include="Assets\1x1\vg.svg"/>
        <AvaloniaResource Include="Assets\1x1\vi.svg"/>
        <AvaloniaResource Include="Assets\1x1\vn.svg"/>
        <AvaloniaResource Include="Assets\1x1\vu.svg"/>
        <AvaloniaResource Include="Assets\1x1\wf.svg"/>
        <AvaloniaResource Include="Assets\1x1\ws.svg"/>
        <AvaloniaResource Include="Assets\1x1\xk.svg"/>
        <AvaloniaResource Include="Assets\1x1\xx.svg"/>
        <AvaloniaResource Include="Assets\1x1\ye.svg"/>
        <AvaloniaResource Include="Assets\1x1\yt.svg"/>
        <AvaloniaResource Include="Assets\1x1\za.svg"/>
        <AvaloniaResource Include="Assets\1x1\zm.svg"/>
        <AvaloniaResource Include="Assets\1x1\zw.svg"/>
        <AvaloniaResource Include="Assets\4x3\ad.svg"/>
        <AvaloniaResource Include="Assets\4x3\ae.svg"/>
        <AvaloniaResource Include="Assets\4x3\af.svg"/>
        <AvaloniaResource Include="Assets\4x3\ag.svg"/>
        <AvaloniaResource Include="Assets\4x3\ai.svg"/>
        <AvaloniaResource Include="Assets\4x3\al.svg"/>
        <AvaloniaResource Include="Assets\4x3\am.svg"/>
        <AvaloniaResource Include="Assets\4x3\ao.svg"/>
        <AvaloniaResource Include="Assets\4x3\aq.svg"/>
        <AvaloniaResource Include="Assets\4x3\ar.svg"/>
        <AvaloniaResource Include="Assets\4x3\arab.svg"/>
        <AvaloniaResource Include="Assets\4x3\as.svg"/>
        <AvaloniaResource Include="Assets\4x3\asean.svg"/>
        <AvaloniaResource Include="Assets\4x3\at.svg"/>
        <AvaloniaResource Include="Assets\4x3\au.svg"/>
        <AvaloniaResource Include="Assets\4x3\aw.svg"/>
        <AvaloniaResource Include="Assets\4x3\ax.svg"/>
        <AvaloniaResource Include="Assets\4x3\az.svg"/>
        <AvaloniaResource Include="Assets\4x3\ba.svg"/>
        <AvaloniaResource Include="Assets\4x3\bb.svg"/>
        <AvaloniaResource Include="Assets\4x3\bd.svg"/>
        <AvaloniaResource Include="Assets\4x3\be.svg"/>
        <AvaloniaResource Include="Assets\4x3\bf.svg"/>
        <AvaloniaResource Include="Assets\4x3\bg.svg"/>
        <AvaloniaResource Include="Assets\4x3\bh.svg"/>
        <AvaloniaResource Include="Assets\4x3\bi.svg"/>
        <AvaloniaResource Include="Assets\4x3\bj.svg"/>
        <AvaloniaResource Include="Assets\4x3\bl.svg"/>
        <AvaloniaResource Include="Assets\4x3\bm.svg"/>
        <AvaloniaResource Include="Assets\4x3\bn.svg"/>
        <AvaloniaResource Include="Assets\4x3\bo.svg"/>
        <AvaloniaResource Include="Assets\4x3\bq.svg"/>
        <AvaloniaResource Include="Assets\4x3\br.svg"/>
        <AvaloniaResource Include="Assets\4x3\bs.svg"/>
        <AvaloniaResource Include="Assets\4x3\bt.svg"/>
        <AvaloniaResource Include="Assets\4x3\bv.svg"/>
        <AvaloniaResource Include="Assets\4x3\bw.svg"/>
        <AvaloniaResource Include="Assets\4x3\by.svg"/>
        <AvaloniaResource Include="Assets\4x3\bz.svg"/>
        <AvaloniaResource Include="Assets\4x3\ca.svg"/>
        <AvaloniaResource Include="Assets\4x3\cc.svg"/>
        <AvaloniaResource Include="Assets\4x3\cd.svg"/>
        <AvaloniaResource Include="Assets\4x3\cefta.svg"/>
        <AvaloniaResource Include="Assets\4x3\cf.svg"/>
        <AvaloniaResource Include="Assets\4x3\cg.svg"/>
        <AvaloniaResource Include="Assets\4x3\ch.svg"/>
        <AvaloniaResource Include="Assets\4x3\ci.svg"/>
        <AvaloniaResource Include="Assets\4x3\ck.svg"/>
        <AvaloniaResource Include="Assets\4x3\cl.svg"/>
        <AvaloniaResource Include="Assets\4x3\cm.svg"/>
        <AvaloniaResource Include="Assets\4x3\cn.svg"/>
        <AvaloniaResource Include="Assets\4x3\co.svg"/>
        <AvaloniaResource Include="Assets\4x3\cp.svg"/>
        <AvaloniaResource Include="Assets\4x3\cr.svg"/>
        <AvaloniaResource Include="Assets\4x3\cu.svg"/>
        <AvaloniaResource Include="Assets\4x3\cv.svg"/>
        <AvaloniaResource Include="Assets\4x3\cw.svg"/>
        <AvaloniaResource Include="Assets\4x3\cx.svg"/>
        <AvaloniaResource Include="Assets\4x3\cy.svg"/>
        <AvaloniaResource Include="Assets\4x3\cz.svg"/>
        <AvaloniaResource Include="Assets\4x3\de.svg"/>
        <AvaloniaResource Include="Assets\4x3\dg.svg"/>
        <AvaloniaResource Include="Assets\4x3\dj.svg"/>
        <AvaloniaResource Include="Assets\4x3\dk.svg"/>
        <AvaloniaResource Include="Assets\4x3\dm.svg"/>
        <AvaloniaResource Include="Assets\4x3\do.svg"/>
        <AvaloniaResource Include="Assets\4x3\dz.svg"/>
        <AvaloniaResource Include="Assets\4x3\eac.svg"/>
        <AvaloniaResource Include="Assets\4x3\ec.svg"/>
        <AvaloniaResource Include="Assets\4x3\ee.svg"/>
        <AvaloniaResource Include="Assets\4x3\eg.svg"/>
        <AvaloniaResource Include="Assets\4x3\eh.svg"/>
        <AvaloniaResource Include="Assets\4x3\er.svg"/>
        <AvaloniaResource Include="Assets\4x3\es.svg"/>
        <AvaloniaResource Include="Assets\4x3\es-ct.svg"/>
        <AvaloniaResource Include="Assets\4x3\es-ga.svg"/>
        <AvaloniaResource Include="Assets\4x3\es-pv.svg"/>
        <AvaloniaResource Include="Assets\4x3\et.svg"/>
        <AvaloniaResource Include="Assets\4x3\eu.svg"/>
        <AvaloniaResource Include="Assets\4x3\fi.svg"/>
        <AvaloniaResource Include="Assets\4x3\fj.svg"/>
        <AvaloniaResource Include="Assets\4x3\fk.svg"/>
        <AvaloniaResource Include="Assets\4x3\fm.svg"/>
        <AvaloniaResource Include="Assets\4x3\fo.svg"/>
        <AvaloniaResource Include="Assets\4x3\fr.svg"/>
        <AvaloniaResource Include="Assets\4x3\ga.svg"/>
        <AvaloniaResource Include="Assets\4x3\gb.svg"/>
        <AvaloniaResource Include="Assets\4x3\gb-eng.svg"/>
        <AvaloniaResource Include="Assets\4x3\gb-nir.svg"/>
        <AvaloniaResource Include="Assets\4x3\gb-sct.svg"/>
        <AvaloniaResource Include="Assets\4x3\gb-wls.svg"/>
        <AvaloniaResource Include="Assets\4x3\gd.svg"/>
        <AvaloniaResource Include="Assets\4x3\ge.svg"/>
        <AvaloniaResource Include="Assets\4x3\gf.svg"/>
        <AvaloniaResource Include="Assets\4x3\gg.svg"/>
        <AvaloniaResource Include="Assets\4x3\gh.svg"/>
        <AvaloniaResource Include="Assets\4x3\gi.svg"/>
        <AvaloniaResource Include="Assets\4x3\gl.svg"/>
        <AvaloniaResource Include="Assets\4x3\gm.svg"/>
        <AvaloniaResource Include="Assets\4x3\gn.svg"/>
        <AvaloniaResource Include="Assets\4x3\gp.svg"/>
        <AvaloniaResource Include="Assets\4x3\gq.svg"/>
        <AvaloniaResource Include="Assets\4x3\gr.svg"/>
        <AvaloniaResource Include="Assets\4x3\gs.svg"/>
        <AvaloniaResource Include="Assets\4x3\gt.svg"/>
        <AvaloniaResource Include="Assets\4x3\gu.svg"/>
        <AvaloniaResource Include="Assets\4x3\gw.svg"/>
        <AvaloniaResource Include="Assets\4x3\gy.svg"/>
        <AvaloniaResource Include="Assets\4x3\hk.svg"/>
        <AvaloniaResource Include="Assets\4x3\hm.svg"/>
        <AvaloniaResource Include="Assets\4x3\hn.svg"/>
        <AvaloniaResource Include="Assets\4x3\hr.svg"/>
        <AvaloniaResource Include="Assets\4x3\ht.svg"/>
        <AvaloniaResource Include="Assets\4x3\hu.svg"/>
        <AvaloniaResource Include="Assets\4x3\ic.svg"/>
        <AvaloniaResource Include="Assets\4x3\id.svg"/>
        <AvaloniaResource Include="Assets\4x3\ie.svg"/>
        <AvaloniaResource Include="Assets\4x3\il.svg"/>
        <AvaloniaResource Include="Assets\4x3\im.svg"/>
        <AvaloniaResource Include="Assets\4x3\in.svg"/>
        <AvaloniaResource Include="Assets\4x3\io.svg"/>
        <AvaloniaResource Include="Assets\4x3\iq.svg"/>
        <AvaloniaResource Include="Assets\4x3\ir.svg"/>
        <AvaloniaResource Include="Assets\4x3\is.svg"/>
        <AvaloniaResource Include="Assets\4x3\it.svg"/>
        <AvaloniaResource Include="Assets\4x3\je.svg"/>
        <AvaloniaResource Include="Assets\4x3\jm.svg"/>
        <AvaloniaResource Include="Assets\4x3\jo.svg"/>
        <AvaloniaResource Include="Assets\4x3\jp.svg"/>
        <AvaloniaResource Include="Assets\4x3\ke.svg"/>
        <AvaloniaResource Include="Assets\4x3\kg.svg"/>
        <AvaloniaResource Include="Assets\4x3\kh.svg"/>
        <AvaloniaResource Include="Assets\4x3\ki.svg"/>
        <AvaloniaResource Include="Assets\4x3\km.svg"/>
        <AvaloniaResource Include="Assets\4x3\kn.svg"/>
        <AvaloniaResource Include="Assets\4x3\kp.svg"/>
        <AvaloniaResource Include="Assets\4x3\kr.svg"/>
        <AvaloniaResource Include="Assets\4x3\kw.svg"/>
        <AvaloniaResource Include="Assets\4x3\ky.svg"/>
        <AvaloniaResource Include="Assets\4x3\kz.svg"/>
        <AvaloniaResource Include="Assets\4x3\la.svg"/>
        <AvaloniaResource Include="Assets\4x3\lb.svg"/>
        <AvaloniaResource Include="Assets\4x3\lc.svg"/>
        <AvaloniaResource Include="Assets\4x3\li.svg"/>
        <AvaloniaResource Include="Assets\4x3\lk.svg"/>
        <AvaloniaResource Include="Assets\4x3\lr.svg"/>
        <AvaloniaResource Include="Assets\4x3\ls.svg"/>
        <AvaloniaResource Include="Assets\4x3\lt.svg"/>
        <AvaloniaResource Include="Assets\4x3\lu.svg"/>
        <AvaloniaResource Include="Assets\4x3\lv.svg"/>
        <AvaloniaResource Include="Assets\4x3\ly.svg"/>
        <AvaloniaResource Include="Assets\4x3\ma.svg"/>
        <AvaloniaResource Include="Assets\4x3\mc.svg"/>
        <AvaloniaResource Include="Assets\4x3\md.svg"/>
        <AvaloniaResource Include="Assets\4x3\me.svg"/>
        <AvaloniaResource Include="Assets\4x3\mf.svg"/>
        <AvaloniaResource Include="Assets\4x3\mg.svg"/>
        <AvaloniaResource Include="Assets\4x3\mh.svg"/>
        <AvaloniaResource Include="Assets\4x3\mk.svg"/>
        <AvaloniaResource Include="Assets\4x3\ml.svg"/>
        <AvaloniaResource Include="Assets\4x3\mm.svg"/>
        <AvaloniaResource Include="Assets\4x3\mn.svg"/>
        <AvaloniaResource Include="Assets\4x3\mo.svg"/>
        <AvaloniaResource Include="Assets\4x3\mp.svg"/>
        <AvaloniaResource Include="Assets\4x3\mq.svg"/>
        <AvaloniaResource Include="Assets\4x3\mr.svg"/>
        <AvaloniaResource Include="Assets\4x3\ms.svg"/>
        <AvaloniaResource Include="Assets\4x3\mt.svg"/>
        <AvaloniaResource Include="Assets\4x3\mu.svg"/>
        <AvaloniaResource Include="Assets\4x3\mv.svg"/>
        <AvaloniaResource Include="Assets\4x3\mw.svg"/>
        <AvaloniaResource Include="Assets\4x3\mx.svg"/>
        <AvaloniaResource Include="Assets\4x3\my.svg"/>
        <AvaloniaResource Include="Assets\4x3\mz.svg"/>
        <AvaloniaResource Include="Assets\4x3\na.svg"/>
        <AvaloniaResource Include="Assets\4x3\nc.svg"/>
        <AvaloniaResource Include="Assets\4x3\ne.svg"/>
        <AvaloniaResource Include="Assets\4x3\nf.svg"/>
        <AvaloniaResource Include="Assets\4x3\ng.svg"/>
        <AvaloniaResource Include="Assets\4x3\ni.svg"/>
        <AvaloniaResource Include="Assets\4x3\nl.svg"/>
        <AvaloniaResource Include="Assets\4x3\no.svg"/>
        <AvaloniaResource Include="Assets\4x3\np.svg"/>
        <AvaloniaResource Include="Assets\4x3\nr.svg"/>
        <AvaloniaResource Include="Assets\4x3\nu.svg"/>
        <AvaloniaResource Include="Assets\4x3\nz.svg"/>
        <AvaloniaResource Include="Assets\4x3\om.svg"/>
        <AvaloniaResource Include="Assets\4x3\pa.svg"/>
        <AvaloniaResource Include="Assets\4x3\pc.svg"/>
        <AvaloniaResource Include="Assets\4x3\pe.svg"/>
        <AvaloniaResource Include="Assets\4x3\pf.svg"/>
        <AvaloniaResource Include="Assets\4x3\pg.svg"/>
        <AvaloniaResource Include="Assets\4x3\ph.svg"/>
        <AvaloniaResource Include="Assets\4x3\pk.svg"/>
        <AvaloniaResource Include="Assets\4x3\pl.svg"/>
        <AvaloniaResource Include="Assets\4x3\pm.svg"/>
        <AvaloniaResource Include="Assets\4x3\pn.svg"/>
        <AvaloniaResource Include="Assets\4x3\pr.svg"/>
        <AvaloniaResource Include="Assets\4x3\ps.svg"/>
        <AvaloniaResource Include="Assets\4x3\pt.svg"/>
        <AvaloniaResource Include="Assets\4x3\pw.svg"/>
        <AvaloniaResource Include="Assets\4x3\py.svg"/>
        <AvaloniaResource Include="Assets\4x3\qa.svg"/>
        <AvaloniaResource Include="Assets\4x3\re.svg"/>
        <AvaloniaResource Include="Assets\4x3\ro.svg"/>
        <AvaloniaResource Include="Assets\4x3\rs.svg"/>
        <AvaloniaResource Include="Assets\4x3\ru.svg"/>
        <AvaloniaResource Include="Assets\4x3\rw.svg"/>
        <AvaloniaResource Include="Assets\4x3\sa.svg"/>
        <AvaloniaResource Include="Assets\4x3\sb.svg"/>
        <AvaloniaResource Include="Assets\4x3\sc.svg"/>
        <AvaloniaResource Include="Assets\4x3\sd.svg"/>
        <AvaloniaResource Include="Assets\4x3\se.svg"/>
        <AvaloniaResource Include="Assets\4x3\sg.svg"/>
        <AvaloniaResource Include="Assets\4x3\sh.svg"/>
        <AvaloniaResource Include="Assets\4x3\sh-ac.svg"/>
        <AvaloniaResource Include="Assets\4x3\sh-hl.svg"/>
        <AvaloniaResource Include="Assets\4x3\sh-ta.svg"/>
        <AvaloniaResource Include="Assets\4x3\si.svg"/>
        <AvaloniaResource Include="Assets\4x3\sj.svg"/>
        <AvaloniaResource Include="Assets\4x3\sk.svg"/>
        <AvaloniaResource Include="Assets\4x3\sl.svg"/>
        <AvaloniaResource Include="Assets\4x3\sm.svg"/>
        <AvaloniaResource Include="Assets\4x3\sn.svg"/>
        <AvaloniaResource Include="Assets\4x3\so.svg"/>
        <AvaloniaResource Include="Assets\4x3\sr.svg"/>
        <AvaloniaResource Include="Assets\4x3\ss.svg"/>
        <AvaloniaResource Include="Assets\4x3\st.svg"/>
        <AvaloniaResource Include="Assets\4x3\sv.svg"/>
        <AvaloniaResource Include="Assets\4x3\sx.svg"/>
        <AvaloniaResource Include="Assets\4x3\sy.svg"/>
        <AvaloniaResource Include="Assets\4x3\sz.svg"/>
        <AvaloniaResource Include="Assets\4x3\tc.svg"/>
        <AvaloniaResource Include="Assets\4x3\td.svg"/>
        <AvaloniaResource Include="Assets\4x3\tf.svg"/>
        <AvaloniaResource Include="Assets\4x3\tg.svg"/>
        <AvaloniaResource Include="Assets\4x3\th.svg"/>
        <AvaloniaResource Include="Assets\4x3\tj.svg"/>
        <AvaloniaResource Include="Assets\4x3\tk.svg"/>
        <AvaloniaResource Include="Assets\4x3\tl.svg"/>
        <AvaloniaResource Include="Assets\4x3\tm.svg"/>
        <AvaloniaResource Include="Assets\4x3\tn.svg"/>
        <AvaloniaResource Include="Assets\4x3\to.svg"/>
        <AvaloniaResource Include="Assets\4x3\tr.svg"/>
        <AvaloniaResource Include="Assets\4x3\tt.svg"/>
        <AvaloniaResource Include="Assets\4x3\tv.svg"/>
        <AvaloniaResource Include="Assets\4x3\tw.svg"/>
        <AvaloniaResource Include="Assets\4x3\tz.svg"/>
        <AvaloniaResource Include="Assets\4x3\ua.svg"/>
        <AvaloniaResource Include="Assets\4x3\ug.svg"/>
        <AvaloniaResource Include="Assets\4x3\um.svg"/>
        <AvaloniaResource Include="Assets\4x3\un.svg"/>
        <AvaloniaResource Include="Assets\4x3\us.svg"/>
        <AvaloniaResource Include="Assets\4x3\uy.svg"/>
        <AvaloniaResource Include="Assets\4x3\uz.svg"/>
        <AvaloniaResource Include="Assets\4x3\va.svg"/>
        <AvaloniaResource Include="Assets\4x3\vc.svg"/>
        <AvaloniaResource Include="Assets\4x3\ve.svg"/>
        <AvaloniaResource Include="Assets\4x3\vg.svg"/>
        <AvaloniaResource Include="Assets\4x3\vi.svg"/>
        <AvaloniaResource Include="Assets\4x3\vn.svg"/>
        <AvaloniaResource Include="Assets\4x3\vu.svg"/>
        <AvaloniaResource Include="Assets\4x3\wf.svg"/>
        <AvaloniaResource Include="Assets\4x3\ws.svg"/>
        <AvaloniaResource Include="Assets\4x3\xk.svg"/>
        <AvaloniaResource Include="Assets\4x3\xx.svg"/>
        <AvaloniaResource Include="Assets\4x3\ye.svg"/>
        <AvaloniaResource Include="Assets\4x3\yt.svg"/>

        <AvaloniaResource Include="Assets\4x3\za.svg"/>
        <AvaloniaResource Include="Assets\4x3\zm.svg"/>
        <AvaloniaResource Include="Assets\4x3\zw.svg"/>
    </ItemGroup>

    <ItemGroup>
      <None Update="Assets\globe.png">
        <Pack>True</Pack>
        <PackagePath>globe.png</PackagePath>
      </None>
    </ItemGroup>

</Project>
